// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGEg1NMiW3YpYw7lYfusUGYzMLukMkOAQ',
    appId: '1:633049195508:web:e27344dedd4138646f4fa1',
    messagingSenderId: '633049195508',
    projectId: 'watchnest-47958',
    authDomain: 'watchnest-47958.firebaseapp.com',
    storageBucket: 'watchnest-47958.firebasestorage.app',
    measurementId: 'G-Z71KTEHKK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNrU34ZK_L1wYjsqPSMG2-pM7WTUiXIo',
    appId: '1:633049195508:android:f9e8c8a8c4fc1a9c6f4fa1',
    messagingSenderId: '633049195508',
    projectId: 'watchnest-47958',
    storageBucket: 'watchnest-47958.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-P1aLKtCHvynNCb7EtjX7fNcv6tCldQ',
    appId: '1:633049195508:ios:4c9da48a9d3f713e6f4fa1',
    messagingSenderId: '633049195508',
    projectId: 'watchnest-47958',
    storageBucket: 'watchnest-47958.firebasestorage.app',
    iosBundleId: 'com.devloper666.watchnest',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-P1aLKtCHvynNCb7EtjX7fNcv6tCldQ',
    appId: '1:633049195508:ios:81a9946c000fe3226f4fa1',
    messagingSenderId: '633049195508',
    projectId: 'watchnest-47958',
    storageBucket: 'watchnest-47958.firebasestorage.app',
    iosBundleId: 'com.example.myTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGEg1NMiW3YpYw7lYfusUGYzMLukMkOAQ',
    appId: '1:633049195508:web:fae3733e20ad76656f4fa1',
    messagingSenderId: '633049195508',
    projectId: 'watchnest-47958',
    authDomain: 'watchnest-47958.firebaseapp.com',
    storageBucket: 'watchnest-47958.firebasestorage.app',
    measurementId: 'G-6BLX9Z9XTY',
  );
}
